application: webappsmm16
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js  

- url: /css
  static_dir: css  

- url: /img
  static_dir: img  

- url: /games
  static_dir: games  
  
- url: /.*
  script: main.application
